export default {
    INITIALIZE_SURVEY: 'INITIALIZE_SURVEY',
    CHANGE_SURVEY_HEADER: 'CHANGE_SURVEY_HEADER',
    CLEAR_SURVEY: 'CLEAR_SURVEY',

    ADD_SECTION: 'ADD_SECTION',
    CHANGE_SECTION_HEADER: 'CHANGE_SECTION_HEADER',
    REMOVE_SECTION: 'REMOVE_SECTION',

    ADD_QUESTION: 'ADD_QUESTION',  
    CHANGE_QUESTION_HEADER: 'CHANGE_QUESTION_HEADER',
    CHANGE_QUESTION_REQUIRED: 'CHANGE_QUESTION_REQUIRED',
    CHANGE_QUESTION_TYPE: 'CHANGE_QUESTION_TYPE',
    REMOVE_QUESTION: 'REMOVE_QUESTION',

    ADD_POSSIBILITY: 'ADD_POSSIBILITY', 
    CHANGE_POSSIBILITY_HEADER: 'CHANGE_POSSIBILITY_HEADER',
    REMOVE_POSSIBILITY: 'REMOVE_POSSIBILITY',
    
    TYPES_OF_QUESTIONS: 'TYPES_OF_QUESTIONS'

};
